const travelDeals = [
  {
    id: 1,
    title: "Explore France’s timeless scenic routes",
    country: "Switzerland",
    duration: "8 Nights - 9 Days",
    rating: 5.0,
    reviews: 325,
    offer: "10% off",
     category: "Honeymoon trip",
    price: 180.0,
    oldPrice: 200.0,
    currency: "USD",
    bigImage:"https://cdn.prod.website-files.com/66920f2a1e03460f2a6e88a5/678e0a705db23bd2a2e59892_Cameroon.avif",
    image:
      "https://cdn.prod.website-files.com/672d8f75dabc438e6086ed62/677b82aea58290c00b2404c1_France%20Four.webp",
    description:
      "Experience the charm of France with scenic drives, rich culture, and timeless beauty across its historic cities.",
    cta: true,
  },
  {
    id: 2,
    title: "Discover Italy’s Romantic Escapes",
    country: "Italy",
    duration: "6 Nights - 7 Days",
    rating: 4.8,
     category: "Honeymoon trip",
    reviews: 210,
    offer: "15% off",
    price: 220.0,
    oldPrice: 260.0,
    currency: "USD",
    image: "https://picsum.photos/seed/italy/400/300",
    bigImage:"https://cdn.prod.website-files.com/66920f2a1e03460f2a6e88a5/678e09ca079a619b76ff4a70_Bhutan%20Background.avif",
    description:
      "Fall in love with Italy’s iconic landmarks, romantic gondola rides in Venice, and authentic Italian cuisine.",
    cta: true,
  },
  {
    id: 3,
    title: "Swiss Alps Adventure",
    country: "Switzerland",
    duration: "5 Nights - 6 Days",
    rating: 4.9,
    reviews: 187,
    offer: "20% off",
    category: "Adventure",
    price: 300.0,
    oldPrice: 375.0,
    currency: "USD",
    image: "https://picsum.photos/seed/switzerland/400/300",
    description:
      "Unwind in the breathtaking landscapes of the Swiss Alps with guided tours, cable car rides, and mountain adventures.",
  },
  {
    id: 4,
    title: "Explore Japan’s Cultural Wonders",
    country: "Japan",
    duration: "9 Nights - 10 Days",
    rating: 4.7,
    reviews: 400,
    offer: "10% off",
     category: "Hiking and trekking",
    price: 450.0,
    oldPrice: 500.0,
    currency: "USD",
    image: "https://picsum.photos/seed/japan/400/300",
    bigImage:"https://cdn.prod.website-files.com/66920f2a1e03460f2a6e88a5/672997a1fbffd955409a219c_Switzerland%20Background.webp",
    description:
      "Immerse yourself in Japan’s traditions, temples, cherry blossoms, and futuristic cityscapes.",
    cta: true,
  },
];

export default travelDeals;
